bifrost:
  # Override the default path to the one used in the docker image
  cert_file: "certs/cert.pem"

bridge:
  name: Bifrost
  mac: bc:24:11:56:21:D1
  ipaddress: 10.0.60.98
  netmask: 255.255.255.0
  gateway: 10.0.60.1
  timezone: Europe/Berlin

z2m:
  server1:
    url: ws://10.0.60.158:8099/api?token=your-secret-token
